# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TGAS5tB5r8-Rf6DIKdmCGCJnBUeSdHA7
"""

import os


#!pip install flask-ngrok

from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications.vgg16 import preprocess_input
#from keras.applications.vgg16 import VGG16
from tensorflow import keras
from keras.models import model_from_json

#print(os.getcwd())

model = keras.models.load_model('btp_model.h5')
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)

model.save_weights("model.h5")
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
loaded_model = model_from_json(loaded_model_json)
loaded_model.load_weights("model.h5")
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
loaded_model.load_weights("model.h5")

#from flask_ngrok import run_with_ngrok
from flask import Flask, render_template, request
app = Flask(__name__)
#run_with_ngrok(app)
@app.route('/',methods=['GET'])
def hello_world():
  return render_template('index.html')

@app.route('/',methods=['POST'])
def predict():
  imagefile = request.files['imagefile']
  image_path = './images/'+imagefile.filename
  imagefile.save(image_path)
  image = load_img(image_path, target_size=(224,224))
  image = img_to_array(image)
  image = image.reshape((1,image.shape[0],image.shape[1],image.shape[2]))
  image = preprocess_input(image)
  yhat = loaded_model.predict(image)
  pred = ""
  if yhat[0][0] == 1:
    pred = "this is defective with probability "+str(yhat[0][0])
  else:
    pred = "this is non defective with probability "+str(yhat[0][1])
  return render_template('index.html', prediction=pred)

app.run()



